apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: aei1njovb-go 
  janus-idp.io/tekton: aei1njovb-go
  backstage.io/kubernetes-id: aei1njovb-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: aei1njovb-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  