apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: aei1njovb-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: aei1njovb-go 
  name: aei1njovb-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: aei1njovb-go 
